#!/bin/bash

# retrieve the list of network interfaces
ifaces=$(ifconfig -a | grep -E "^([a-zA-Z0-9]+)" | awk '{print $1}')

# iterate over each network interface and retrieve its IP address
for iface in $ifaces; do
  ip=$(ifconfig $iface | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')
  
  # check if the IP address is not empty and is an IPv4 address
  if [[ ! -z $ip && $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Interface $iface has IP address: $ip"
  fi
done
